default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: deploy
  password: pointer
development:
  <<: *default
  database: music-studio-api_development
test:
  <<: *default
  database: music-studio-api_test
production:
  <<: *default
  database: music-studio-api_production
